# -*- coding: utf-8 -*-
"""orden ascendente.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ss4LtcJR7mVER8Ixw2JKIoiKI_6L98Sj
"""

# Un algoritmo que lea tres números y los imprima ordenados ascendentemente.
# Define los tres números
num1 = 5
num2 = 10
num3 = 9

# Coloca los números en una lista
numeros = [num1, num2, num3]

# Ordena la lista en orden ascendente
numeros.sort()

# Imprime los números ordenados
print(numeros)